version: '3.4'

services:
  # coinservice:
  #   restart: always
  #   build:
  #     context: ./Backend
  #     dockerfile: CoinService/Dockerfile
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5002:5432
    volumes:
      - /Docker/postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: CoinDB