version: 1
jobs:
  backend_build:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet build

  backend_test:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet test

  backend_publish:
    docker:
      - image: microsoft/dotnet:2.2.100-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet publish -c Release

workflows:
  version: 2
  build:
    jobs:
      - backend_build
      - backend_test:
          requires:
            - backend_build
      - backend_publish:
          requires:
            - backend_test